run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  # Report everything, including issues that pre-date this config.
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
